 var app=angular.module("myApp",[]);
app.controller("myCtrl",function($scope){
  $scope.fruits=[
  {name:'Apple',image:'apple.jpg',description:'An apple is a sweet, edible fruit produced by an apple tree. Apple trees are cultivated worldwide, and are the most widely grown species in the genus Malus.                                                                          ',price:'100'},
  {name:'Mango',image:'mango.jpg',description:'Mangoes are juicy stone fruit from numerous species of tropical trees belonging to the flowering plant genus Mangifera, cultivated mostly for their edible fruit. The majority of these species are found in nature as wild mangoes. ',price:'200'},
  {name:'Pineapple',image:'pineapple.jpg',description:'The pineapple is a tropical plant with an edible multiple fruit consisting of coalesced berries, also called pineapples, and the most economically significant plant in the family Bromeliaceae. ',price:'150'},
  {name:'Cherry',image:'cherry.jpg',description:'A cherry is the fruit of many plants of the genus Prunus, and is a fleshy drupe. The cherry fruits of commerce usually are obtained from cultivars of a limited number of species such as the sweet cherry and the sour cherry',price:'120'},
  {name:'Orange',image:'orange.jpg',description:'The orange is the fruit of the citrus species Citrus × sinensis in the family Rutaceae. It is also called sweet orange, to distinguish it from the related Citrus × aurantium, referred to as bitter orange.',price:'100'},
  {name:'Banana',image:'banana.jpg',description:'A banana is an edible fruit – botanically a berry – produced by several kinds of large herbaceous flowering plants in the genus Musa. In some countries, bananas used for cooking may be called "plantains", distinguishing them from dessert bananas.',price:'90'},
  {name:'Pears',image:'Pears.jpg',description:'The pear is any of several tree and shrub species of genus Pyrus, in the family Rosaceae. It is also the name of the pomaceous fruit of the various trees. Several species of pear are valued for their edible fruit and juices while others are cultivated as trees.',price:'100'},
  {name:'Berries',image:'berries.jpg',description:'A berry is a small, pulpy, and often edible fruit. Berries are typically juicy, rounded, brightly colored, sweet or sour, and do not have a stone or pit, although many pips or seeds may be present. Common examples are strawberries, raspberries, blueberries, blackberries, red currants, white currants and blackcurrants. ',price:'110'},
  {name:'Melons',image:'melon.jpg',description:'A melon is any of various plants of the family Cucurbitaceae with sweet edible, fleshy fruit. The word "melon" can refer to either the plant or specifically to the fruit. Botanically, a melon is a kind of berry, specifically a "pepo".',price:'200'},
  {name:'KiwiFruits',image:'kiwifruit.jpg',description:'Kiwifruit, or Chinese gooseberry is the edible berry of several species of woody vines in the genus Actinidia. The most common cultivar group of kiwifruit is oval, about the size of a large hens egg. It has a fibrous, dull greenish-brown skin and bright green or golden flesh with rows of tiny, black, edible seeds',price:'50'},
  {name:'Strawberry',image:'strawberry.jpg',description:'The garden strawberry is a widely grown hybrid species of the genus Fragaria, collectively known as the strawberries. It is cultivated worldwide for its fruit. The fruit is widely appreciated for its characteristic aroma, bright red color, juicy texture, and sweetness.',price:'80'},
  {name:'Plums',image:'plums.jpg',description:'A plum is a fruit of the subgenus Prunus of the genus Prunus. The subgenus is distinguished from other subgenera in the shoots having terminal bud and solitary side buds, the flowers in groups of one to five together on short stems, and the fruit having a groove running down one side and a smooth stone.',price:'60'}];
});
